---
title: Data and Visualization
author: Bharat Bhushan Verma
date: '2021-05-18'
slug: data-visualization-using-ggplot2
categories:
  - ggplot2
tags: []
lastmod: '2021-05-18T03:15:00-03:00'
keywords: []
description: ''
comment: no
toc: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---
## Dataset Terminology

```{r message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(Tmisc)
starwars
```

```{r}
glimpse(starwars)
```

## Mass Vs Height
```{r warning=FALSE}
ggplot(data = starwars, mapping = aes(x = height, y = mass)) +
  geom_point() +
  labs(title = "Mass vs. height of Starwars characters",
       x = "Height (cm)", y = "Weight (kg)")
```

## Anscombe's Quartet
```{r echo=FALSE, }
quartet %>%
  group_by(set) %>%
  summarise(
    mean_x = mean(x), 
    mean_y = mean(y),
    sd_x = sd(x),
    sd_y = sd(y),
    r = cor(x, y)
  )
```

```{r echo=FALSE}
ggplot(quartet, aes(x = x, y = y)) +
  geom_point() +
  facet_wrap(~ set, ncol = 4)
```



